name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - dot

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.1.2
        env:
          QODANA_TOKEN: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJvcmdhbml6YXRpb24iOiIzb0RycCIsInByb2plY3QiOiIzb0x2bCIsInRva2VuIjoiQUcybloifQ.tbZxnXYrfjlzK7ceqzmFUX8S96nrT2W7I6ORCEupLWc"
        with:
          pr-mode: true